steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  entrypoint: bash
  args: ['-c', 'gcloud config set app/cloud_build_timeout 240']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  args: [ app, deploy, --version=$SHORT_SHA, --stop-previous-version, app.yaml ]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  args: [ app, deploy, cron.yaml ]
timeout: 240s
